name: Minify and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Встановити Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Встановити пакети для мінімізації
        run: npm install -g clean-css-cli uglify-js html-minifier

      - name: Мінімізувати CSS, JS та HTML
        run: |
          cleancss -o style.css style.css
          uglifyjs script.js -o script.js --compress --mangle
          html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --minify-css true --minify-js true -o index.html index.html

      - name: Деплой на GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .  
